### ISSUE TITLE
When is the 1.5 release?

### ISSUE THREAD

**Issue by bitbrain** [libgdx/box2dlights#100]
Hello guys,

I am currently developing a [little game engine](https://github.com/bitbrain/braingdx) based on libgdx. Unfortunately I depend on the 1.5 release since it contains a certain feature (rendering box2dlights inside `FrameBuffer` objects). Right now I patched some  v1.5 files directly into my project to be compatible. However, since I am using Continious Integration I would like to not depend on those patch files but having the 1.5 release in my pom.xml.

Do you have a roughly release date already?

**Comment by bitbrain** [comment]
@badlogic any news on this?

**Comment by rinold** [comment]
@bitbrain Hi,

Sorry for inconveniences, I've fallen out for a long time. I'll revise the changelog today - have a strong feeling it have some info missing, and will request guys to push the 1.5 release. Hope it would be available soon, will try to deadline myself to have it available by the end of this week (hope sooner).

**Comment by bitbrain** [comment]
Hello @rinold thanks for the quick response! If a 1.5 release is blocked by anything, I would be even happy with a 1.4.x hotfix which includes PR https://github.com/libgdx/box2dlights/pull/90 which is what I am interested in.

**Comment by rinold** [comment]
@bitbrain, for now it's only changelog and possibly the issue #95 - haven't had a Mac OS to test and fix it for a long time, will check it and if it still reproduces but can't be fixed easily will leave it for later, think the 1.5 was delayed too much already.
