### ISSUE TITLE
invalid sha1

### ISSUE THREAD

**Issue by JulienBe** [libgdx/box2dlights#103]
Heyllo !

Looks like the sha1 on https://repo1.maven.org/maven2/com/badlogicgames/box2dlights/box2dlights/1.4/ is invalid.
I compute `1759928402bb809fef9df8989cb24a1ce08645e8  box2dlights-1.4.pom` where it's expected to be `eefc40a640a45eeabe749ab9c980fd94c9e529e3`

Thanks for your work :+1:

**Comment by rinold** [comment]
I compute the 1759928402bb809fef9df8989cb24a1ce08645e8 also... Seems something gone wrong.
Does this have any impact, or you just found out this occasionally?)

**Comment by JulienBe** [comment]
Well I use sbt and it verifies the hash by default. I have turned it off

**Comment by SimonIT** [comment]
1.5 is the latest, so I'll close this one
