### ISSUE TITLE
Not compatible with Libgdx1.9.7

### ISSUE THREAD

**Issue by Trurl101** [libgdx/box2dlights#107]
With Libgdx 1.9.7 box2d crashes on android:

```
W/System.err: java.lang.NoSuchMethodError: No direct method <init>(Lcom/badlogic/gdx/graphics/Pixmap$Format;IIZ)V in class Lcom/badlogic/gdx/graphics/glutils/FrameBuffer; or its super classes (declaration of 'com.badlogic.gdx.graphics.glutils.FrameBuffer' appears in /data/app/xxx/base.apk)
W/System.err:     at box2dLight.LightMap.<init>(LightMap.java:120)
W/System.err:     at box2dLight.RayHandler.resizeFBO(RayHandler.java:142)
W/System.err:     at box2dLight.RayHandler.<init>(RayHandler.java:131)
```

**Comment by rinold** [comment]
Oh, 1.9.7 introduced breaking changes in FrameBuffer. Will check it.

**Comment by Trurl101** [comment]
A yesterdays [libgdx patch](https://github.com/libgdx/libgdx/commit/c5fed1006b816fddf899b9e16826a4578a373114) fixed the problem for now. At least for the latest libgdx snapshot.

**Comment by RafalRybowski** [comment]
I have this problem too. I start with libgdx and don't know how to repair this

**Comment by rinold** [comment]
It's the 1.9.7 issue only (afaik). Should work with [recomended versions](https://libgdx.badlogicgames.com/versions.html).

**Comment by RafalRybowski** [comment]
thx @rinold i go down and work

**Comment by crykn** [comment]
Closing this, since 1.9.8 was released nearly three years ago.
