### ISSUE TITLE
RayHadler initialization exception

### ISSUE THREAD

**Issue by mgolebiowski95** [libgdx/box2dlights#125]
Hi

I have a little problem. When I upgrade gdxVection from 1.9.13 to 1.9.14 I got this error:

org.lwjgl.opengl.OpenGLException: Cannot use offsets when Pixel Unpack Buffer Object is disabled

by invoking RayHandler(world)

I try to run the desktop application.

**Comment by Tom-Ski** [comment]
This is a libgdx problem, and was solved in 1.9.15-SNAPSHOT. Downgrade to 1.9.13 and wait for the 1.9.15 release or use the 1.9.15-SANSPHOT

**Comment by mgolebiowski95** [comment]
Thank you for fast response. Thanks
