### ISSUE TITLE
Bodies with multiple fixtures block light rays from lights attached to the body.

### ISSUE THREAD

**Issue by seannybgoode** [libgdx/box2dlights#36]
Found the issue in libGDX 1.4.1 running box2dLights. Using RUBE to get multiple fixtured bodies on the go for some advanced collision detection, but when I attach a light to the body, the fixtures block the light rays. I can work around, but thought I should let you guys know.

**Comment by rinold** [comment]
Hi @seannybgoode, have you checked it yet? I'm going to close this issue.

**Comment by seannybgoode** [comment]
Hi, sorry we haven't had a chance to check. We ended up using Filters to
have the light not collide with the fixtures.
