### ISSUE TITLE
FitViewport issue

### ISSUE THREAD

**Issue by postpunkpl** [libgdx/box2dlights#41]
Hello,

I have a problem with rendering my game with box2dlights and FitViewport option.

My project use  gdxVersion = 1.5.3 and box2dlights:1.2 or 1.3.

I use macbook pro with Eclipse and test my game for Desktop.

I have a ortho camera and FitViewport:

my renderer create method:

```java
...
camera = new OrthographicCamera(640, 320);
viewport = new FitViewport(640, 320, camera);
camera.position.set(camera.viewportWidth / 2f, camera.viewportHeight / 2f, 0);
camera.update();
...
```

my renderer render method:

```java
camera.update();
....
batch.setProjectionMatrix(camera.combined);
....
rayHandler.setCombinedMatrix(camera.combined);
rayHandler.updateAndRender();
```

my resize() method:

```java
renderer.getViewport().update(width, height);

renderer.getCamera().position.set(
				renderer.getCamera().viewportWidth / 2,
				renderer.getCamera().viewportHeight / 2, 0);

stage.getViewport().update(width, height, false);
```

after changing window size without using box2dlights my screen looks like this:

http://i59.tinypic.com/w12wb5.png

after changing windows size with box2dlights my screen looks like this:

http://i59.tinypic.com/2qmof3r.png

So it's looks like adding box2dlights disable correct work of FitViewport or i have a bug in my code.

I have no idea what is wrong with my code :(

**Comment by rinold** [comment]
Hi @postpunkpl,

From the version 1.3 the best way is to use the camera itself for setting combined matrix:
```java
rayHandler.setCombinedMatrix(camera)
```

Also for the correct viewport rendering if not using default values you should set it manually (in resize method):
```java
rayHandler.useCustomViewport(x, y, width, height);
```
Where the x, y, width and height are the values of your custom viewport.

**Comment by postpunkpl** [comment]
Hi Mikhail!

Thank You very much! It works perfectly! :)

Greetings

Peter

**Comment by rinold** [comment]
You are welcome!

I will hold this issue open for a while, until the info on the Wiki will be created regarding the box2dlights custom viewport usage - it seems be quite useful, but missing currently.

**Comment by postpunkpl** [comment]
Hello Mikhail,

I'm sorry to bother you, but i have again problem with FitViewports.
Could you be so nice and look at this post?:

http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=18362&p=77183#p77183

Greetings

Peter

2015-02-09 16:44 GMT+01:00 Mikhail Churbanov <notifications@github.com>:

**Comment by rinold** [comment]
Added Wiki page
