### ISSUE TITLE
Set Falloff of lights

### ISSUE THREAD

**Issue by haimat** [libgdx/box2dlights#42]
it would be really great if one could set the falloff value of a light source. What I want to achieve is a very bright light, but with basically (very low) distance. Full brightness on one spot, no softness whatsoever. But only for some lights.

Would that be easy to implement?

**Comment by rinold** [comment]
For what it should be used? I mean if this will not have to deal with things like shadows or complex lighting of the underlying environment, than I suppose not to complicate the things and use the simple small spot sprites instead, which as I think could produce the same effect but without thousands of useless checks and iterations in lighting engine :)

**Comment by haimat** [comment]
In such a case using just a sprite is not an issue. Think of a very dark scene (i.e. low ambient light), then without light source you would hardly see the sprite any more.

**Comment by rinold** [comment]
You can use following render scenario:
1. Render light-affected scene elements
2. Render lighting (rayHandler.render)
3. Render light-not-affected elements (e.g. spot sprites, UI, other things)

In that case everything rendered at point 3 will not be covered by ambient light.

**Comment by haimat** [comment]
Yes, I guess hat is correct.
I will think about that solution, thanks!

**Comment by haimat** [comment]
Well, there is one problem with this approach: I need to render various elements in a certain order. When I would now render thos not-light-affected sprites after the rayHandler, then those will always be on top of eveything else. That is not really the expected behaviour :-(

**Comment by rinold** [comment]
Well, the lights are rendered in one pass also and they are also on top of everything rendered before. There is a problem anyway :(

**Comment by haimat** [comment]
True, it's a tricky thing...
Well, nevermind, it's not that important.
The pseudo-3d feature is what I am really looking for :-)
