### ISSUE TITLE
Latest box2dlights version not in Maven

### ISSUE THREAD

**Issue by haimat** [libgdx/box2dlights#46]
After you have kindly fixed the `ScreenUtils` bug I would like to use the new box2dlights version. However, it seems the latest version 1.4 is not in Maven, so I cannot use it in my Gradle build. The snapshot of 1.4 however does already contain the latest update:

http://libgdx.badlogicgames.com/box2dlights/

Are there any plans to release latest version 1.4 to Maven central anytime soon?

**Comment by rinold** [comment]
I'll need to make a few stuff before releasing 1.4, but I will try do it may be in a couple of weeks.
