### ISSUE TITLE
Create method for adding light to RayHandler

### ISSUE THREAD

**Issue by felipefcm** [libgdx/box2dlights#50]
Instead of inserting light after creating new instance, create a method to add light to RayHandler.
I think that the current behaviour is not much common, given that in various situations you want to create the light but not immediately start to use it, or even have created RayHandler instance yet.

**Comment by rinold** [comment]
The method to add light exists, but no possibility to create light without RayHandler, ops...

**Comment by felipefcm** [comment]
I forgot that I could just create the light in 'not active' state until needed. Thanks!
