### ISSUE TITLE
Camera rotation can break lighting

### ISSUE THREAD

**Issue by thebnich** [libgdx/box2dlights#55]
Whenever the camera is rotated >90 degrees in either direction, the lighting suddenly breaks (i.e., the screen goes black). Simple test case [here](https://gist.github.com/thebnich/91de3109dcd7dd9639c9).

**Comment by rinold** [comment]
Have you tried the
```java
   rayHandler.setCombinedMatrix(viewport.getCamera());
```
instead of
```java
   rayHandler.setCombinedMatrix(viewport.getCamera().combined);
```

And also could you check if the issue relates to the [custom viewport](https://github.com/libgdx/box2dlights/wiki/Custom-viewport-and-box2dlights)?

**Comment by thebnich** [comment]
>```
rayHandler.setCombinedMatrix(viewport.getCamera());
```

Interesting, that does work. Thanks!

**Comment by rinold** [comment]
As it works only for simple scenarios and sometimes such questions are raised I will keep it open to not to forget to deprecate (and possibly remove) the usage of:
```java
rayHandler.setCombinedMatrix(viewport.getCamera().combined);
```
