### ISSUE TITLE
RFE: expose RayNum in Light

### ISSUE THREAD

**Issue by AlchemicTempest** [libgdx/box2dlights#56]
There is no way from outside to get the RayNum of a Light.
Meaning it would completely suffice to have a "int getRayNum()"

Why would you ever need this? I am placing lights with my map editor, in the map editor I want to keep track of how many rays a light has, disable it, make it editable. And for obvious reasons I dont want to save this number myself for each light when its already in there.

**Comment by rinold** [comment]
Should be available in next build/release :)
