### ISSUE TITLE
Create Spot light

### ISSUE THREAD

**Issue by felipefcm** [libgdx/box2dlights#63]
Create a Spot light type, which could be just a point light with limited radius range and constant falloff.

**Comment by rinold** [comment]
Hi, sorry for a late answer, just to clarify - you mean that the SpotLight should be like the PointLight except one that it is not appropriate for your usage, cause it has no constant falloff and provides the same illumination inside of it's range - and you want the shadow to be linear growing from point light center to it's borders?

**Comment by felipefcm** [comment]
Thanks for the answer. I'm afraid that I used the term 'falloff' in a wrong way, I thought it was the rate of intensity drop from the center, but it looks like it's an angle value that determines where the drop actually starts. I just imagined some sort of 'prison light', it basically have constant intensity inside the circle and virtually none out of it's radius. That effect can be achieved using a point light?

**Comment by rinold** [comment]
I'm afraid the problem was in my non-nativeness of english :)
However, I think yes - the PointLight should behave the way you described. You can also try the test project in box2dlights where all light types should be present to see if their behavior will be acceptable for your needs.
