### ISSUE TITLE
box2dlights doesnot work with libGDX 1.6.2

### ISSUE THREAD

**Issue by azakhary** [libgdx/box2dlights#65]
Since latest change in libGDX in [commit 9036b80...](https://github.com/libgdx/libgdx/commit/9036b801cc3f4844d346dc96bf9b8f89d8390ad0#diff-d636cdcb18994566054d0d18f8b91c71)

when using  rayHandler.updateAndRender(); 
it throws weird error: [see stacktrace](http://pastebin.com/gRVjfctL)

**how to reproduce**
1) Create empty libgdx project using setup app, and make sure to use libgdx 1.6.2
2) use [this source](http://pastebin.com/p6Fv9u3x) as example: 

@xoppa suggested that [this](https://github.com/libgdx/box2dlights/blob/master/pom.xml#L52) might be the problem.

But I am not sure, because no matter the version, method is still there, it is just in a parent class now.

Any idea what this might be?

**Comment by Tom-Ski** [comment]
Just needed a rebuild against the latest LibGDX due to changes in FrameBuffer, this is fixed in 1.4-SNAPSHOT.
