### ISSUE TITLE
Box2dlights 1.3 , robovm 1.4.0 , libgdx 1.6.3 -> NoSuchMethodError

### ISSUE THREAD

**Issue by tajny** [libgdx/box2dlights#67]
It seems 1.6.2 broke this 

```
java.lang.NoSuchMethodError: com.badlogic.gdx.graphics.glutils.FrameBuffer.getColorBufferTexture()Lcom/badlogic/gdx/graphics/Texture;
    at box2dLight.LightMap.gaussianBlur(LightMap.java:76)
    at box2dLight.LightMap.render(LightMap.java:37)
    at box2dLight.RayHandler.render(RayHandler.java:328)
    at box2dLight.RayHandler.updateAndRender(RayHandler.java:262)
```

**Comment by rinold** [comment]
Have you tried latest box2dlights 1.4?

**Comment by shiro900** [comment]
Exactly the same error. I have been frustrated for the last 10 hours trying to fix it. I also posted on stackoverflow http://gamedev.stackexchange.com/questions/104026/box2d-lights-error-from-the-example-code

**Comment by rileyrg** [comment]
Updating the gradle dependency to box2dlights 1.4fixed this for me after moving to snapshot 1.6.4

compile "com.badlogicgames.box2dlights:box2dlights:1.4"
