### ISSUE TITLE
RayHandler.setAmbientLight() doesn't seem to work

### ISSUE THREAD

**Issue by adam-law** [libgdx/box2dlights#70]
No matter what value I set to "brighten" things up e.g. 0.1f to 1f or greater than 1f, it still stays the same shade of dark. I can confirm lights work great. Since there's no official DirectionalLight for top-down, adjusting ambient lighting is probably the next best thing. 

If this is normal behavior, could it be amended so ambient lighting can be bright as day / dark as night?

Thanks.

**Comment by rinold** [comment]
Just to clarify, are you talking about setAmbientLight() not working for pseudo-3d branch or in both?

**Comment by adam-law** [comment]
sorry to only see this now rinold. I haven't checked out the pseudo-3d branch yet, if ambient light worked the way I understand it to work, then it would do for my project, for now.

**Comment by adam-law** [comment]
I think I know what the problem was, I was using a darker base color. switching to white made things work. sorry for the bother.
