### ISSUE TITLE
Generating shadow from 2d image

### ISSUE THREAD

**Issue by wingoku** [libgdx/box2dlights#71]
I wanted know if I can generate a shadow from a 2d image. For example: I have a coke cane and I want to generate a shadow such that it drops on the table or horizontal surface on right side of the coke. Then I want to create an image/bitmap of the coke & shadow combined. A little bit of hints will be very helpful.

**Comment by crykn** [comment]
Considering this question was posted over 5 years ago, I'm closing this. For future questions, our [Discord](https://libgdx.com/community/) server would be a better place.
