### ISSUE TITLE
FREQ - Light flicker

### ISSUE THREAD

**Issue by adam-law** [libgdx/box2dlights#77]
I was thinking that it would be possible to simulate flickering lights, particularly for flame-like lights if light offsets could have options to be tied to box2d horizontal gravity, or have this effect be done internally in box2dlights. I know it's quite possible to do the offset calculation outside of box2dlights, but it'd be convenient if it's built in, so that everything is neatly tied to one render step.

**Comment by piotr-j** [comment]
Feels like something trivial to implement with `Light#setDistance()` unless im missing something obvious.
