### ISSUE TITLE
[Feature Request] Pixel Art Lights

### ISSUE THREAD

**Issue by chelinho139** [libgdx/box2dlights#89]
hello, we are developing a Pixel Art Game and using Box2dLights.
However, given that we are using pixel art, lights do not look so good..

We would prefer if there was a way to make lights look like this:
![heroes-of-loot-playstation-vita-1](https://cloud.githubusercontent.com/assets/7676795/10495366/e23ce038-7291-11e5-97ab-5af13ce5c01a.png)

Is there a way to create this style of lights? I read at the forums that it is posible something like changing  the framebuffer size or something like that..

Any ideas? And  can it be something posible that it comes in a future update??
Thanks..
The Team.

**Comment by rinold** [comment]
The rayHandler constructor can accept the frame buffer sizes, by default it's sizes are 
```java
(Gdx.graphics.getWidth() / 4, Gdx.graphics.getHeight() / 4
```

You can try to make it smaller to have more pixelated lights, also if this will not help, could you please try to disable the blurring - which makes lights look smoother (by default it's also enabled):
```java
rayHandler.setBlur(false)
```
