### ISSUE TITLE
Licence information

### ISSUE THREAD

**Issue by SebastianSchlegel** [libgdx/box2dlights#96]
On the [old google code page](https://code.google.com/archive/p/box2dlights/) you could see which license is used by box2dlights:

> License: Apache License 2.0

The current github page is missing this information, or am I missing something?

**Comment by nanodeath** [comment]
The pom.xml file still has that license listed.

**Comment by SimonIT** [comment]
Seem to be resolved with https://github.com/libgdx/box2dlights/commit/37e719a170cc8750ccc86d092df92db6e9bebed2
