### ISSUE TITLE
lightList in RayHandler is not accessible

### ISSUE THREAD

**Issue by lampione** [libgdx/box2dlights#97]
The editor keep marking as error the usage of lightList with the following message:

'lightList' is not public in 'box2dLight.RayHandler'. Cannot be accessed from outside package.
the project won't build until I comment out the line.

I'm using version 1.4 with gradle

**Comment by rinold** [comment]
This is done intentionally, manual modification of this list might lead to issues. Could you please provide the reason why you need access to this list?

**Comment by lampione** [comment]
I wanted to get a valid reference to all the lights. Simply. That's not a big deal. Thank you!

**Comment by rinold** [comment]
Actually this list contains only active lights, valid but disabled lights will not be in it. Also they could be moved from one list to another, so better to store needed lights in your own code.

**Comment by nanodeath** [comment]
I would like something like this, too. Would it possibly make sense to implement something like `com.badlogic.ashley.core.Engine`'s `addEntityListener` method? (and `removeEntityListener`) That way it'd be easy to "subscribe" to additions, removals, that sort of thing, and maintain a separate list if desired there.
